name: Bare Minimum Requirements

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bare Minimum Requirements
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
        path: node_modules
        key: npm-packages-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
          if: steps.cache.outputs.cache-hit != 'true'
          run: npm install
      - run: npm run lint
      if: ${{ always() }}
      - run: npm run tsc
        if: ${{ always() }}
      - run: npm run build
        if: ${{ always() }}

